CREATE TABLESPACE  TS_BDP4_2019
DATAFILE  'C:\BD\TS_BDP4_2019.dbf' SIZE 1M 
AUTOEXTEND ON;

CREATE USER USER_PRATICA04
IDENTIFIED BY aluno
DEFAULT TABLESPACE TS_BDP4_2019
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_BDP4_2019;

GRANT DBA TO USER_PRATICA04 WITH ADMIN OPTION;